
#ifndef __AMBA_VSRC_PRIV_H__
#define __AMBA_VSRC_PRIV_H__

#define MAX_ENCODE_STREAMS	3

#define MAX_NUM_STREAMS		4
#define NUM_CLUTS			(MAX_NUM_STREAMS * NUM_OVERLAY_AREAS)

#define CLUT_ENTRY_SIZE		1024
#define OVERLAY_OFFSET		(NUM_CLUTS * CLUT_ENTRY_SIZE)

enum vsrc_status_e {
	STATE_UNKNOWN,
	STATE_IDLE,
	STATE_PREVIEW,
	STATE_ENCODING,
};

#define AMODE(_name)		AMBA_VIDEO_MODE_##_name

#define INTERLACED		AMBA_VIDEO_FORMAT_INTERLACE
#define PROGRESSIVE		AMBA_VIDEO_FORMAT_PROGRESSIVE

#define AR_AUTO			AMBA_VIDEO_RATIO_AUTO
#define AR_4_3			AMBA_VIDEO_RATIO_4_3
#define AR_16_9			AMBA_VIDEO_RATIO_16_9

#define SYS_AUTO		AMBA_VIDEO_SYSTEM_AUTO
#define NTSC			AMBA_VIDEO_SYSTEM_NTSC
#define PAL				AMBA_VIDEO_SYSTEM_PAL

#endif

