#ifndef __Camera_Window_Registration_h__
#define __Camera_Window_Registration_h__

#define WINDOW_poweroff            "PowerOffWnd"
#define WINDOW_usb_storage         "USBStorageWnd"
#define WINDOW_carmountunplug      "CarMountUnplugWnd"
#define WINDOW_spacefull           "SpaceFullWnd"
#define WINDOW_cardmissing         "CardMissingWnd"
#define WINDOW_diskerror           "WriteDiskErrorWnd"
#define WINDOW_UnknownFormat       "UnknowSDFormatWnd"
#define WINDOW_highlight           "HighlightWnd"
#define WINDOW_highlight_failed    "HighlightFailedWnd"
#define WINDOW_obd_connected       "OBDConnectedWnd"
#define WINDOW_obd_disconnected    "OBDDisconnectedWnd"
#define WINDOW_hid_connected       "HIDConnectedWnd"
#define WINDOW_hid_disconnected    "HIDDisconnectedWnd"
#define WINDOW_OBD_not_binded      "OBDNotBindedWnd"
#define WINDOW_HID_not_binded      "HIDNotBindedWnd"
#define WINDOW_overheat            "OverheatWnd"

#define WINDOW_shotcuts            "Wnd-shotcuts"
#define WINDOW_gauges              "Wnd-gauges"
#define WINDOW_settingsgauges      "Wnd-settingsgauges"

#define WINDOW_videomenu           "VideoMenuWnd"
#define WINDOW_videoquality        "VideoQualityWnd"
#define WINDOW_audiomenu           "AudioMenuWnd"
#define WINDOW_spkvolume           "SpeakerVolumeMenuWnd"
#define WINDOW_displaymenu         "DisplayMenuWnd"
#define WINDOW_brightnessmenu      "BrightnessMenuWnd"
#define WINDOW_screensaver_settings "ScreenSaverSettingsWnd"
#define WINDOW_displayoffmenu      "DisplayOffMenuWnd"
#define WINDOW_rotation_menu       "RotationModeWnd"
#define WINDOW_screensaver_style   "ScreenSaverStyleWnd"
#define WINDOW_autooffmenu         "AutoOffMenuWnd"
#define WINDOW_storagemenu         "StorageMenuWnd"
#define WINDOW_formatTF            "FormatTFWnd"
#define WINDOW_advancedmenu        "AdvancedMenuWnd"
#define WINDOW_versionmenu         "VersionMenuWnd"
#define WINDOW_factory_reset_menu  "FactoryResetWnd"
#define WINDOW_timemenu            "TimeDateMenuWnd"
#define WINDOW_timeformat          "TimeFormatMenuWnd"
#define WINDOW_dateformat          "DateFormatMenuWnd"
#define WINDOW_wifimenu            "WifiMenuWnd"
#define WINDOW_btmenu              "BluetoothMenuWnd"
#define WINDOW_hid_detail          "HIDDetailWnd"
#define WINDOW_obd_detail          "OBDDetailWnd"
#define WINDOW_wifimodemenu        "WifiModeMenuWnd"
#define WINDOW_autohotspot_menu    "AutoAPMenuWnd"
#define WINDOW_wifi_detail         "WifiDetailWnd"
#define WINDOW_wifi_no_connection  "WifiNoConnectWnd"
#define WINDOW_obd_preferences     "OBDMenuWnd"

#define WINDOW_screen_saver        "ScreenSaverWnd"

#define WINDOW_touch               "Wnd-touch"
#define WINDOW_ColorTest           "ColorPalleteWnd"
#define WINDOW_fpstest             "Wnd-fpstest"
#define WINDOW_debug_menu          "DebugMenuWnd"
#define WINDOW_wifi_mode_test      "Wnd-wifi_mode_test"
#define WINDOW_wifi_signal_test    "WifiSignalDebugWnd"
#define WINDOW_wav_play            "WavPlayWnd"
#define WINDOW_gps_test            "GPSDebugWnd"
#define WINDOW_units_test          "UnitsWnd"

#define WINDOW_60mph_countdown     "CountdownTestWnd"
#define WINDOW_60mph_auto          "AutoTestWnd"
#define WINDOW_test_score          "TestScoreWnd"

#endif

